import { Glob } from "bun";
import { join } from "path";
import { execSync } from "node:child_process";

interface TestCase {
  description: string;
  data: unknown;
  valid: boolean;
}

interface TestGroup {
  description: string;
  schema: unknown;
  tests: TestCase[];
}

const drafts = ["draft3", "draft4", "draft6", "draft7", "draft2019-09", "draft2020-12"];
const officialTestsDir = join(import.meta.dir, "..", "official-tests", "tests");

const testSuiteCommit = execSync("git -C official-tests rev-parse HEAD", { encoding: "utf-8" }).trim();
const { version: packageVersion } = await Bun.file(join(import.meta.dir, "..", "package.json")).json();

const data: Record<string, Record<string, TestGroup[]>> = {};

for (const draft of drafts) {
  const draftDir = join(officialTestsDir, draft);
  const glob = new Glob("**/*.json");
  const files: string[] = [];

  for (const match of glob.scanSync(draftDir)) {
    files.push(match);
  }

  files.sort();

  if (files.length === 0) continue;

  data[draft] = {};

  for (const file of files) {
    const fullPath = join(draftDir, file);
    const content = await Bun.file(fullPath).text();
    const groups: TestGroup[] = JSON.parse(content);
    const key = file.replace(/\.json$/, "");
    data[draft][key] = groups;
  }

  console.log(`${draft}: ${Object.keys(data[draft]).length} test files`);
}

const output = `// Auto-generated by src/build-test-data.ts — do not edit manually.

export const packageVersion = ${JSON.stringify(packageVersion)};

export const testSuiteCommit = ${JSON.stringify(testSuiteCommit)};

export interface TestCase {
  description: string;
  data: unknown;
  valid: boolean;
  [key: string]: unknown;
}

export interface TestGroup {
  description: string;
  schema: unknown;
  tests: TestCase[];
  [key: string]: unknown;
}

export const testData: Record<string, Record<string, TestGroup[]>> = ${JSON.stringify(data, null, 2)};
`;

const outPath = join(import.meta.dir, "test-data.ts");
await Bun.write(outPath, output);
console.log(`\nWrote ${outPath}`);
